version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sb-event-s3-upload-csv-file"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bg0hn61q1kso"
s3_prefix = "sb-event-s3-upload-csv-file"
region = "us-east-2"
profile = "sbadmin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
