---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
  S3InvokeFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Path to the Code
      CodeUri: s3-read-csv/
      # Path to the lamdbda handler
      Handler: app.lambda_handler
      # Python Runtime
      Runtime: python3.9
      # Time after which the execution of the Lambda Stops.
      Timeout: 60 
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: s3:GetObject*
              Resource: !Sub "arn:aws:s3:::${AWS::StackName}-${AWS::Region}-${AWS::AccountId}*"
      Events:
        Upload:
          Type: S3
          Properties:
            Bucket: 
              Ref: Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .csv
    
  
