# These lines 2 and 3 are mandatory for all SAM Templates
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless app 

  Template for servless app.

Resources:
  UploadTOS3BucketFunction:   
   Type: AWS::Serverless::Function
   Properties:
    FunctionName: GetS3Buckets
    Description: Lambda function which gets the S3 buckets
    CodeUri: upload-s3-bucket/
    Handler: app.lambda_handler
    Runtime: python3.9
    Timeout: 60
    Architectures:
        - x86_64
    

Outputs:
  GetS3BucketsFunction:
    Description: "Upload TO S3 Bucket Function ARN"
    Value: !GetAtt UploadTOS3BucketFunction.Arn
  
