# These lines 2 and 3 are mandatory for all SAM Templates
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless app 

  Template for servless app.

Resources:
  DynamodbInvokeFunction:   
   Type: AWS::Serverless::Function
   Properties:
    FunctionName: DynamodbInvoke
    Description: Lambda function which gets the S3 buckets
    CodeUri: dynamodb-invoke/
    Handler: app.lambda_handler
    Runtime: python3.9
    Timeout: 60
    Architectures:
        - x86_64
    
Outputs:
  DynamodbInvokeFunction:
    Description: "Get S3 Buckets Function ARN"
    Value: !GetAtt DynamodbInvokeFunction.Arn
 